### ISSUE TITLE
Waffe: 21Desert Eagle (24)

### ISSUE THREAD

**Issue by OrdeneauxBiggar377** [SAMPTools/Fahrzeug-und-Spielerinformationen-Overlay#2]
Hi, habe, wenn ich mich nicht irre einen kleinen Bug entdeckt.
Sobald man eine Desert Eagle besitzt, erscheint eine 21 vor dem Namen, also 21Desert Eagle (ID:24)
Wofür steht die 21? Ich nehme mal an die soll da weg, weil das bei anderen Waffen nicht der Fall ist.

Hier ein Bild zur Verdeutlichung:

http://imgur.com/F0us8hl

**Comment by konstantinschuette** [comment]
Danke für den Hinweis!
In der SAMP-UDF ist jede Waffen-ID mit einem Namen verbunden. Warum auch immer habe ich bei dem Namen der Desert Eagle, eine "21" davor geschrieben.
Der Fehler wurde behoben. Einfach noch mal neu herunterladen.

Danke für das Melden des Fehlers!

**Comment by Suchty112** [comment]
Das ist leider auch so in der SAMP-UDF drinne, der Fehler liegt nicht bei dir sondern bei mir bzw dem Ersteller der Funktion. ^^
